---
# vars file for roles/configure-packages

brew_packages:
  install:
    - cosign
    - ansible-lint
    - yamllint
    - terragrunt
    - tenv
    - awscli
    - cli53
    - jq
    - tree
    - gnupg
    - graphviz
    - openjdk
    - go

  uninstall:
    - kubectl
    - kubectx
    - helm
    - minikube
    - pulumi
    - gsed
    - rust
    - php
    - composer
    - scala
    - scalacenter/bloop/bloop
    - mysql-client@8.4

brew_casks:
  install:
    - docker
    - visual-studio-code
    - adobe-acrobat-reader
    - the-unarchiver

  uninstall:
    - dbeaver-community
    - google-chrome
    - lastpass
    - slack
    - zoom

brew_taps:
  install:
    - hashicorp/tap/terraform
    - homeport/tap/dyff

  uninstall:

node_versions:
  - 22.12.0

terraform_versions:
  - 1.10.3

terragrunt_versions:
  - 0.71.1

vscode_extensions:
  - redhat.ansible
  - GitHub.vscode-pull-request-github
  - ms-azuretools.vscode-docker
  - ms-vscode.cpptools
  - golang.Go
  - rust-lang.rust-analyzer
  - ms-python.python
  - Oracle.oracle-java
  - scala-lang.scala
  - HashiCorp.terraform
  - mechatroner.rainbow-csv
  - ms-vscode.makefile-tools
  - HashiCorp.HCL
